import nodeTest from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {clone,parseBackup,validateBackup,exportBackup,startWorkout,finishWorkout,templateFrom,ordered,dateInput,emptyBackup} from '../lib/backup.mjs';
// The personal backup stays outside Git; CI runs the synthetic suite instead.
const fixture=new URL('../../edzesnaplo-2026-08-20.json',import.meta.url);
const available=fs.existsSync(fixture);
const test=(name,run)=>nodeTest(name,{skip:!available},run);
const input=available?fs.readFileSync(fixture,'utf8'):'{}';
const original=JSON.parse(input);
test('Actual backup imports all original data without normalizing fields',()=>{assert.deepEqual(parseBackup(input),original);assert.equal(original.workouts.length,66);assert.equal(original.exercises.length,96);assert.equal(original.templates.length,6);assert.equal(original.bodyweights.length,11);});
test('Untouched backup round trip is deeply equal except export timestamp',()=>{const out=parseBackup(exportBackup(parseBackup(input)));out.exported=original.exported;assert.deepEqual(out,original);});
test('Unknown future fields are retained at every level',()=>{const d=clone(original);d.custom={theme:'a'};d.workouts[0].extra=[1,2];d.workouts[0].exercises[0].extra='x';d.workouts[0].exercises[0].sets[0].extra=true;assert.deepEqual(parseBackup(exportBackup(d,new Date(d.exported))),d);});
test('All supplied PRs match rounded Epley estimates',()=>{const prs={};for(const w of original.workouts)for(const e of w.exercises)for(const s of e.sets)prs[e.exerciseId]=Math.max(prs[e.exerciseId]||0,Math.round(s.weight*(1+s.reps/30)*10)/10);for(const [id,value] of Object.entries(original.prs))assert.equal(prs[id],value);});
test('New workout exports and reimports while preserving all previous records',()=>{const d=clone(original),w=startWorkout(d,ordered(d.workouts)[0]);w.exercises[0].sets[0]={weight:301.5,reps:8};const out=parseBackup(exportBackup(finishWorkout(d,w)));assert.equal(out.workouts.length,67);assert.deepEqual(out.workouts.slice(0,66),original.workouts);assert.deepEqual(out.exercises,original.exercises);assert.deepEqual(out.templates,original.templates);assert.deepEqual(out.bodyweights,original.bodyweights);assert.deepEqual(d,original);assert.equal(out.prs[w.exercises[0].exerciseId],381.9);assert.ok(out.workouts[66].endTime);});
test('Editing retains id, times, unknown metadata and count',()=>{const d=clone(original);const w=clone(d.workouts[0]);w.custom=7;w.exercises[0].sets[0].weight=1;const next=finishWorkout(d,w);assert.equal(next.workouts.length,66);assert.equal(next.workouts[0].id,w.id);assert.equal(next.workouts[0].custom,7);assert.equal(next.workouts[0].startTime,w.startTime);assert.equal(next.workouts[0].endTime,w.endTime);assert.deepEqual(next.workouts.slice(1),d.workouts.slice(1));});
test('Template start uses most recent sets, isolates copies and retains template',()=>{const d=clone(original),t=d.templates[0],w=startWorkout(d,t,true);assert.equal(w.notes,t.name);for(const e of w.exercises){const prev=ordered(d.workouts).flatMap(x=>x.exercises).find(x=>x.exerciseId===e.exerciseId);assert.deepEqual(e.sets,prev.sets);}w.exercises[0].sets[0].weight=999;assert.deepEqual(d,original);assert.deepEqual(Object.keys(templateFrom(w,'New')).sort(),['exercises','id','name']);assert.equal(templateFrom(w,'New').exercises[0].sets,undefined);});
test('Invalid or unsupported imports fail without mutating current data',()=>{for(const bad of ['nope','{}',JSON.stringify({...original,version:3}),JSON.stringify({...original,workouts:[original.workouts[0],original.workouts[0]]}),JSON.stringify({...original,prs:null})])assert.throws(()=>parseBackup(bad));assert.deepEqual(JSON.parse(input),original);});
test('Empty or partially typed sets cannot finish',()=>{const d=clone(original);assert.throws(()=>finishWorkout(d,startWorkout(d)));for(const bad of ['',-1,NaN,Infinity]){const w=startWorkout(d,d.workouts[0]);w.exercises[0].sets[0].weight=bad;assert.throws(()=>finishWorkout(d,w));}for(const reps of ['',0,-1,1.5]){const w=startWorkout(d,d.workouts[0]);w.exercises[0].sets[0].reps=reps;assert.throws(()=>finishWorkout(d,w));}});
test('Dates are stable for old timestamps and imported zero weights are supported',()=>{assert.equal(dateInput(1773964800000),'2026-03-20');const d=clone(original);d.workouts[0].exercises[0].sets[0].weight=0;validateBackup(d);assert.equal(ordered(original.workouts)[0].id,'mt0cdect5ik1');});
test('UTF-8 BOM and empty valid backups are supported',()=>{assert.deepEqual(parseBackup('\ufeff'+input),original);validateBackup(emptyBackup());});

