import test from 'node:test';
import assert from 'node:assert/strict';
import {clone,emptyBackup,exportBackup,parseBackup,finishWorkout} from '../lib/backup.mjs';
import {exerciseProfile,previousExercise,recommendAlternatives,replaceExercise,undoReplacement} from '../lib/exercise-swap.mjs';
const e=(id,name,muscle,tags=[])=>({id,name,muscle,muscles:tags});
function fixture(){const data=emptyBackup();data.exercises=[e('press','Gépi mellnyomás','Mell',['chest','triceps']),e('bench','Fekvenyomás rúddal','Mell',['chest','triceps']),e('db','Fekvenyomás síkpadon (súlyzó)','Mell',['chest','triceps']),e('incline','Fekvenyomás döntött padon (súlyzó)','Mell',['chest-upper','triceps']),e('fly','Tárogatás gépen','Mell',['chest']),e('shoulder','Vállból nyomás gépen','Váll'),e('custom','Saját ismeretlen gyakorlat','Mell')];data.workouts=[{id:'old',date:1000,notes:'Előzmény',exercises:[{exerciseId:'db',name:data.exercises[2].name,muscle:'Mell',sets:[{weight:15,reps:12,custom:'old-set-data'}]}]}];const draft={id:'active',date:2000,notes:'Mai edzés',startTime:2000,custom:{keep:1},exercises:[{exerciseId:'press',name:'Gépi mellnyomás',muscle:'Mell',sets:[{weight:80,reps:8}],extra:{keep:1}},{exerciseId:'fly',name:'Tárogatás gépen',muscle:'Mell',sets:[{weight:40,reps:10}]}]};return {data,draft};}
test('Recommendations match movement, exclude current/used and unrelated exercises',()=>{const {data,draft}=fixture();const r=recommendAlternatives(data,draft.exercises[0],draft);assert.deepEqual(r.map(x=>x.exercise.id),['db','bench','incline']);assert.ok(r[0].reason.includes('Mellnyomás'));assert.ok(r[0].notes.some(n=>n.includes('stabilizálást')));assert.ok(r[2].notes.some(n=>n.includes('testhelyzet')));});
test('Equipment filter never returns a different equipment type',()=>{const {data,draft}=fixture();assert.deepEqual(recommendAlternatives(data,draft.exercises[0],draft,{equipment:'barbell'}).map(r=>r.exercise.id),['bench']);assert.deepEqual(recommendAlternatives(data,draft.exercises[0],draft,{equipment:'cable'}),[]);});
test('Same broad muscle does not equate knee extension and knee flexion',()=>{const {data,draft}=fixture();data.exercises=[e('legpress','Lábprés (leg press)','Láb'),e('squat','Guggolás (back squat)','Láb'),e('curl','Ülő lábhajlítás gépen','Láb'),e('extension','Lábnyújtás gépen','Láb')];draft.exercises=[{exerciseId:'legpress',...data.exercises[0],sets:[]}];assert.deepEqual(recommendAlternatives(data,draft.exercises[0],draft).map(r=>r.exercise.id),['squat']);assert.notEqual(exerciseProfile(data.exercises[2]).movement,exerciseProfile(data.exercises[3]).movement);});
test('Unknown names do not generate unsupported recommendations',()=>{const {data,draft}=fixture();assert.deepEqual(recommendAlternatives(data,{exerciseId:'custom'},draft),[]);assert.equal(exerciseProfile(e('x','Oldalsó plank','Has')).movement,'sidePlank');assert.notEqual(exerciseProfile(e('x','Plank','Has')).movement,exerciseProfile(e('y','Hasprés','Has')).movement);});
test('Replacement retains workout order, uses its own history and keeps other data immutable',()=>{const {data,draft}=fixture(),before=clone({data,draft});const result=replaceExercise(data,draft,0,'db');assert.deepEqual(result.draft.exercises[0].sets,[{weight:15,reps:12}]);assert.equal(result.draft.exercises[0].exerciseId,'db');assert.equal(result.draft.exercises[0].name,data.exercises[2].name);assert.equal(result.draft.exercises[0].extra,undefined);assert.deepEqual(result.draft.exercises[1],draft.exercises[1]);assert.deepEqual(result.draft.custom,draft.custom);assert.deepEqual({data,draft},before);});
test('Without history replacement requires explicitly entered values',()=>{const {data,draft}=fixture();const result=replaceExercise(data,draft,0,'bench');assert.deepEqual(result.draft.exercises[0].sets,[{weight:'',reps:''}]);assert.throws(()=>finishWorkout(data,result.draft));});
test('History excludes the workout being edited and uses the most recent record',()=>{const {data,draft}=fixture();data.workouts.push({...clone(data.workouts[0]),id:'newer',date:1500});data.workouts[1].exercises[0].sets[0].weight=17.5;data.workouts.push({...clone(data.workouts[1]),id:draft.id,date:3000});data.workouts[2].exercises[0].sets[0].weight=99;assert.equal(previousExercise(data,'db',draft.id).exercise.sets[0].weight,17.5);});
test('Undo restores full original metadata and refuses to erase newer edits',()=>{const {data,draft}=fixture();const result=replaceExercise(data,draft,0,'db');assert.deepEqual(undoReplacement(result.draft,result.undo),draft);result.draft.exercises[0].sets[0].weight=20;assert.throws(()=>undoReplacement(result.draft,result.undo));});
test('Invalid, duplicate or stale replacements fail without changing the draft',()=>{const {data,draft}=fixture(),before=clone(draft);for(const [i,id] of [[-1,'db'],[20,'db'],[0,'missing'],[0,'press'],[0,'fly']])assert.throws(()=>replaceExercise(data,draft,i,id));assert.deepEqual(draft,before);});
test('Completed swapped workout round-trips in the legacy schema without swap metadata',()=>{const {data,draft}=fixture();const result=replaceExercise(data,draft,0,'db');const out=parseBackup(exportBackup(finishWorkout(data,result.draft)));assert.equal(out.workouts[1].exercises[0].exerciseId,'db');assert.deepEqual(out.workouts[0],data.workouts[0]);assert.deepEqual(out.templates,data.templates);assert.equal(out.undo,undefined);assert.equal(out.workouts[1].undo,undefined);});
