import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyBackup,startWorkout,exportBackup} from '../lib/backup.mjs';
import {hydrateMeta,withDraft,moveDraft} from '../lib/session.mjs';
import {writeSnapshot,readSnapshot,exportSnapshot,importSnapshot} from '../lib/persistence.mjs';
function fixture(){const data=emptyBackup(),draft=startWorkout(data);draft.exercises=[{exerciseId:'a',name:'Press',muscle:'Mell',sets:[{weight:40,reps:8},{weight:'',reps:''}]}];const meta=hydrateMeta(data,draft);meta.activity.checks[0][0]=true;meta.exerciseNotes.a='Ülés: 4\nHáttámla: 2';return {data,draft,meta};}
function storage(){let value=null;return {getItem:()=>value,setItem:(k,v)=>{value=v;}};}
test('Checkpoint survives reload with incomplete fields and checks, without closing workout',()=>{const s=storage(),{data,draft,meta}=fixture();const saved=writeSnapshot(s,'key',null,data,draft,meta,12345);const restored=readSnapshot(s.getItem('key'));assert.deepEqual(restored.draft,draft);assert.equal(restored.meta.activity.checks[0][0],true);assert.equal(restored.meta.savedAt,12345);assert.equal(restored.data.workouts.length,0);assert.equal(restored.draft.endTime,undefined);assert.equal(saved.value,s.getItem('key'));});
test('Full backup roundtrip preserves active workout, notes, timer and unknown legacy data',()=>{const x=fixture();x.data.extra={keep:1};x.meta.timer={end:999999,remaining:60};assert.deepEqual(importSnapshot(exportSnapshot(x.data,x.draft,x.meta)),x);assert.equal(importSnapshot(exportBackup(x.data)).meta,null);const legacy=JSON.parse(exportBackup(x.data));assert.equal(legacy.meta,undefined);assert.equal(legacy.draft,undefined);assert.deepEqual(legacy.extra,{keep:1});});
test('Exercise notes persist into subsequent workouts without following list positions',()=>{const {data,draft,meta}=fixture();const next=withDraft(meta,startWorkout(data));assert.equal(next.exerciseNotes.a,meta.exerciseNotes.a);draft.exercises.push({exerciseId:'b',name:'Other',muscle:'Mell',sets:[]});meta.activity.checks.push([]);const r=moveDraft(draft,meta,0,1);assert.equal(r.meta.exerciseNotes[r.draft.exercises[1].exerciseId],'Ülés: 4\nHáttámla: 2');});
test('Quota failure does not overwrite the last checkpoint or report success',()=>{const s=storage(),x=fixture();const saved=writeSnapshot(s,'k',null,x.data,x.draft,x.meta,1);s.setItem=()=>{throw new Error('QuotaExceededError');};x.draft.notes='unsaved';assert.throws(()=>writeSnapshot(s,'k',saved.value,x.data,x.draft,x.meta,2),/Nem sikerült/);assert.notEqual(readSnapshot(s.getItem('k')).draft.notes,'unsaved');assert.equal(readSnapshot(s.getItem('k')).meta.savedAt,1);});
test('Concurrent tab writes and silently dropped writes are detected',()=>{const s=storage(),x=fixture();assert.throws(()=>writeSnapshot(s,'k','stale',x.data,x.draft,x.meta),/másik/);s.setItem=()=>{};assert.throws(()=>writeSnapshot(s,'k',null,x.data,x.draft,x.meta),/Nem sikerült/);});
test('Corrupted full backups are rejected without mutating data',()=>{const x=fixture();const malformed=JSON.parse(exportSnapshot(x.data,x.draft,x.meta));malformed.draft.exercises[0].sets='bad';assert.throws(()=>importSnapshot(JSON.stringify(malformed)));malformed.draft=x.draft;malformed.meta.exerciseNotes.a=12;assert.throws(()=>importSnapshot(JSON.stringify(malformed)));});
