'use client';
import {useEffect,useRef,useState} from 'react';
import {Dumbbell,Upload,Download,Plus,ArrowUpRight,ArrowLeft,Check,Trash2,BookOpen,Activity,Layers,Settings,Search,ShieldCheck,Timer,Play,Pause,RotateCcw,ArrowLeftRight} from 'lucide-react';
import ExerciseSwapDialog from '../components/exercise-swap-dialog';
import WorkoutEditor from '../components/workout-editor';
import TemplateCard from '../components/template-card';
import WorkoutCalendar from '../components/workout-calendar';
import {hydrateMeta,withDraft,counts,completedWorkout,swapSession,moveItem,saveTemplateOrder,exportedMeta,reminderDue} from '../lib/session.mjs';
import {clone,parseBackup,validateBackup,exportBackup,emptyBackup,startWorkout,finishWorkout,templateFrom,newId,today,dateInput,ordered,volume} from '../lib/backup.mjs';
import {readSnapshot,exportSnapshot,importSnapshot,writeSnapshot} from '../lib/persistence.mjs';

type Row=Record<string,any>;
const KEY='edzesnaplom-v2';
const fmt=(n:number)=>new Intl.NumberFormat('hu-HU',{maximumFractionDigits:1}).format(n);
const date=(n:number)=>new Intl.DateTimeFormat('hu-HU',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(n);
function download(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
export default function Home(){
 const [data,setData]=useState<Row|null>(null),[draft,setDraft]=useState<Row|null>(null),[ready,setReady]=useState(false),[view,setView]=useState('naplo'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[pick,setPick]=useState(false),[selected,setSelected]=useState<Row|null>(null),[pending,setPending]=useState<Row|null>(null),[weight,setWeight]=useState(''),[weightDate,setWeightDate]=useState(today()),[exerciseName,setExerciseName]=useState(''),[muscle,setMuscle]=useState('Egyéb'),[progressId,setProgressId]=useState(''),[offline,setOffline]=useState(false);
 const [swapIndex,setSwapIndex]=useState<number|null>(null),[undoState,setUndoState]=useState<Row|null>(null),[swapError,setSwapError]=useState('');
 const [diaryMode,setDiaryMode]=useState('list');
 const [pendingSession,setPendingSession]=useState<Row|null>(null);
 const [meta,setMeta]=useState<Row>(()=>hydrateMeta(emptyBackup(),null));
 const raw=useRef<string|null>(null),blocked=useRef(false),file=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!pending&&!pick&&swapIndex===null)return;const previous=document.activeElement as HTMLElement|null;const modal=document.querySelector<HTMLElement>('[role="dialog"]');const focusable=()=>Array.from(modal?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not([hidden]),select,[tabindex="0"]')||[]);focusable()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPending(null);setPick(false);setSwapIndex(null);}if(e.key==='Tab'){const items=focusable(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[pending,pick,swapIndex]);
 useEffect(()=>{try{raw.current=localStorage.getItem(KEY);if(raw.current){const saved=readSnapshot(raw.current);setData(validateBackup(saved.data));setDraft(saved.draft||null);setMeta(hydrateMeta(saved.data,saved.draft||null,saved.meta));if(saved.draft&&!saved.meta&&!saved.data.workouts.some((w:Row)=>w.id===saved.draft.id))setNotice('A folyamatban lévő edzésed megmaradt. Jelöld be, melyik sorozatokat végezted már el.');if(saved.draft){setView('edzes');setNotice('A félbehagyott edzés visszaállítva, a sorozatokkal és pipákkal együtt.');}}}catch(e){blocked.current=true;setError('A helyi mentés nem olvasható. Előbb töltsd le a sérült tárolót az alábbi gombbal; az app nem írja felül.');}setReady(true);
 navigator.storage?.persist?.().catch(()=>{});
 const change=(e:StorageEvent)=>{if(e.key===KEY){blocked.current=true;setError('A napló egy másik böngészőlapon megváltozott. Töltsd újra ezt az oldalt a folytatáshoz.');}};window.addEventListener('storage',change);
 if('serviceWorker' in navigator && process.env.NODE_ENV==='production')navigator.serviceWorker.register((process.env.NEXT_PUBLIC_BASE_PATH || '')+'/sw.js').then(()=>navigator.serviceWorker.ready).then(()=>setOffline(true)).catch(()=>{});
 return()=>window.removeEventListener('storage',change);},[]);
 function persist(next:Row,nextDraft:Row|null=draft,nextMeta:Row=meta){if(blocked.current)throw new Error('A tároló védelme miatt most nem lehet menteni. Töltsd újra az oldalt.');if(localStorage.getItem(KEY)!==raw.current){blocked.current=true;throw new Error('Egy másik böngészőlap módosította a naplót. Töltsd újra ezt az oldalt.');}const saved=writeSnapshot(localStorage,KEY,raw.current,next,nextDraft,nextMeta);raw.current=saved.value;setData(next);setDraft(nextDraft);setMeta(saved.meta);setUndoState(null);setError('');}
 function commitEdit(next:Row,nextDraft:Row|null,nextMeta:Row,label?:string){const before=label?clone({data,draft,meta,view}):null;persist(next,nextDraft,nextMeta);if(before)setUndoState({...before,label});}
 function act(fn:()=>void){try{fn();}catch(e){setError(e instanceof Error?e.message:'Nem sikerült a művelet.');}}
 function edit(fn:(d:Row)=>void){if(!draft||!data)return;act(()=>{const next=clone(draft);fn(next);persist(data,next,hydrateMeta(data,next,meta));});}
 function begin(source:Row|null=null,template=false){if(!data)return;if(draft){setView('edzes');setNotice('A folyamatban lévő edzésed megnyílt. Fejezd be vagy vesd el az új edzés előtt.');return;}act(()=>{const w=startWorkout(data,source,template),m=withDraft(meta,w);m.timer={end:null,remaining:m.defaultRest};persist(data,w,m);setView('edzes');setSelected(null);});}
 function performSwap(id:string){if(!data||!draft||swapIndex===null)return;try{const result=swapSession(data,draft,meta,swapIndex,id);commitEdit(data,result.draft,result.meta,'Gyakorlatcsere');setSwapIndex(null);setNotice('Gyakorlat kicserélve. Az új sorozatokat külön pipáld ki.');}catch(e){setSwapError((e as Error).message);}}
 function save(){if(!data||!draft)return;act(()=>{const c=counts(draft,meta);if(!c.done)throw new Error('Előbb pipálj ki legalább egy elvégzett sorozatot.');if(c.pending&&!confirm(c.done+' elvégzett sorozat kerül a naplóba, '+c.pending+' ki nem pipált sorozat kimarad. Lezárod az edzést?'))return;const result=completedWorkout(data,draft,meta);commitEdit(result.data,null,result.meta,'Edzés mentése');setView('naplo');setSelected(null);setNotice('Az elvégzett sorozatokat elmentettem. Szép munka!');});}
 function exportData(){if(data)act(()=>{download(exportBackup(data),'edzesnaplo-'+today()+'.json');if(!blocked.current)persist(data,draft,exportedMeta(meta));setNotice(draft?'Mentés letöltve. A folyamatban lévő edzés a lezárása után kerül az exportba.':'Kompatibilis JSON-mentés letöltve.');});}
 function checkpoint(){if(data&&draft)act(()=>{persist(data,draft,meta);setNotice('Edzés mentve folytatáshoz. Nyitva marad; újratöltés után innen folytathatod.');});}
 function exportFull(){if(data)act(()=>{download(exportSnapshot(data,draft,meta),'edzesnaplom-teljes-'+today()+'.json');setNotice('Teljes mentés letöltve: napló, félbehagyott edzés, pipák és gyakorlatmegjegyzések.');});}
 async function importFile(f?:File){if(!f)return;try{if(f.size>30*1024*1024)throw new Error('A mentés túl nagy (legfeljebb 30 MB lehet).');const parsed=importSnapshot(await f.text());setPending(parsed.data);setPendingSession(parsed);setError('');}catch(e){setError((e as Error).message);}if(file.current)file.current.value='';}
 function confirmImport(){if(!pending)return;act(()=>{if(data){localStorage.setItem(KEY+'-previous',JSON.stringify({data,draft,meta}));download(exportSnapshot(data,draft,meta),'edzesnaplom-import-elott-'+today()+'.json');}const m=withDraft({...meta,dirtyWorkoutIds:[],remindAfter:5,lastExportAt:null,timer:{end:null,remaining:meta.defaultRest}},null);persist(pending,pendingSession?.draft||null,pendingSession?.meta||m);setPending(null);setPendingSession(null);setSelected(null);setView(pendingSession?.draft?'edzes':'naplo');setNotice('A mentés betöltve. Folytathatod az edzést.');navigator.storage?.persist?.().catch(()=>{});});}
 const snapshot=useRef({data,draft});snapshot.current={data,draft};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_workout_summary',title:'Edzésnapló összegzése',description:'Az ezen az eszközön betöltött napló és a folyamatban lévő edzés összegzése.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Üres objektum szükséges.');const s=snapshot.current;return {loaded:!!s.data,workouts:s.data?.workouts.length||0,templates:s.data?.templates.length||0,activeWorkout:s.draft?.notes||null};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const workouts=data?ordered(data.workouts):[],last=workouts[0],filtered=workouts.filter((w:Row)=>(w.notes+' '+w.exercises.map((e:Row)=>e.name).join(' ')).toLocaleLowerCase('hu').includes(search.toLocaleLowerCase('hu')));
 const exercises=data?.exercises.filter((e:Row)=>(e.name+' '+e.muscle).toLocaleLowerCase('hu').includes(search.toLocaleLowerCase('hu')))||[];
 const nav=[['naplo','Napló',BookOpen],['sablon','Sablonok',Layers],['gyakorlat','Gyakorlatok',Dumbbell],['fejlodes','Fejlődés',Activity],['mentes','Mentések',Settings]] as const;
 const banners=<>{error&&<div role="alert" className="banner error">{error}{blocked.current&&<button onClick={()=>{download(raw.current||'','helyi-tarolo-mentes.json');}}>Helyi tároló letöltése</button>}</div>}{notice&&<div role="status" className="banner">{notice}<button aria-label="Üzenet bezárása" onClick={()=>setNotice('')}>×</button></div>}</>;
 const importer=<input ref={file} hidden type="file" accept=".json,application/json" onChange={e=>importFile(e.target.files?.[0])}/>;
 const importReview=pending&&<div className="overlay"><section role="dialog" aria-modal="true" aria-labelledby="import-title" className="modal"><span className="eyebrow">MENTÉS ELLENŐRIZVE</span><h2 id="import-title">Minden készen áll a folytatáshoz.</h2><div className="stats"><div><strong>{pending.workouts.length}</strong><small>edzés</small></div><div><strong>{pending.exercises.length}</strong><small>gyakorlat</small></div><div><strong>{pending.templates.length}</strong><small>sablon</small></div></div><p>{pending.bodyweights.length} testsúlymérés · Mentés: {date(Date.parse(pending.exported))}</p>{pendingSession?.meta&&<p>Teljes alkalmazásmentés: gyakorlatmegjegyzések és beállítások{pendingSession.draft?', valamint egy félbehagyott edzés':''} is visszaállnak.</p>}{data&&<p>A betöltés lecseréli a jelenlegi naplót és a folyamatban lévő edzést. Előtte automatikusan letöltünk egy biztonsági másolatot; az előző állapotot helyben is megőrizzük.</p>}<div className="actions"><button className="secondary" onClick={()=>setPending(null)}>Mégse</button><button className="primary" onClick={confirmImport}>Mentés betöltése <ArrowUpRight size={18}/></button></div></section></div>;
 if(!ready)return <main className="welcome"><div className="brand"><Dumbbell/> EDZÉSNAPLÓM</div><p>Napló megnyitása…</p></main>;
 if(!data)return <main className="welcome">{importer}<div className="brand"><Dumbbell/> EDZÉSNAPLÓM</div>{banners}<span className="eyebrow">FOLYTASD, AHOL ABBAHAGYTAD</span><h1>A következő ismétlés<br/><em>már itt kezdődik.</em></h1><p>Töltsd be az Edzésnapló biztonsági mentését. Az edzéseid, gyakorlataid és sablonjaid együtt érkeznek.</p><button className="primary" onClick={()=>file.current?.click()}><Upload size={20}/> Mentés megnyitása</button><button className="text-button" onClick={()=>act(()=>persist(emptyBackup(),null))}>Üres napló indítása</button><small><ShieldCheck size={18}/> Az adataid ezen az eszközön maradnak.</small><p className="hint">Első alkalommal válaszd az edzesnaplo-2026-08-20.json fájlt. Másik eszközre az exportált mentés betöltésével viheted át az edzéseidet.</p>{importReview}</main>;
 return <div className="shell">{importer}<aside className="sidebar"><div className="brand"><Dumbbell/> EDZÉSNAPLÓM</div><span className="sidebar-caption">A TE TEMPÓDBAN.</span><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setSearch('');setSelected(null);}}><Icon size={20}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><span className="status-dot"/> Ezen az eszközön mentve<small>{offline?'Offline használatra kész':'Saját, helyi napló'}</small></div></aside><main className="content"><header className="topbar"><span>{new Date().toLocaleDateString('hu-HU',{year:'numeric',month:'long',day:'numeric'})}</span><button className="icon-button" onClick={exportData} aria-label="JSON-mentés letöltése"><Download size={20}/></button></header>{banners}{undoState&&<div className="banner undo-banner" role="status"><span>{undoState.label}. A következő módosításig visszavonható.</span><button onClick={()=>act(()=>{const previous=undoState;persist(previous.data,previous.draft,previous.meta);setSelected(null);setView(previous.view);setNotice('Az előző állapot visszaállítva.');})}><RotateCcw size={17}/> Visszavonás</button></div>}{reminderDue(meta)&&<div className="backup-reminder" role="status"><div><strong>Ideje biztonsági mentést készíteni</strong><p>{meta.dirtyWorkoutIds.length} új vagy módosított edzés az utolsó export óta.</p></div><div className="actions"><button className="primary" onClick={exportData}><Download size={18}/> Mentés letöltése</button><button className="text-button" onClick={()=>act(()=>persist(data,draft,{...meta,remindAfter:meta.dirtyWorkoutIds.length+1}))}>Következő edzés után</button></div></div>}{draft&&view!=='edzes'&&<button className="resume" onClick={()=>setView('edzes')}><span><span className="status-dot"/> Folyamatban: {draft.notes||'Új edzés'}</span><span>Folytatás →</span></button>}
 {view==='naplo'&&!selected&&<div className="diary-view-switch" role="group" aria-label="Napló nézete"><button aria-pressed={diaryMode==='list'} onClick={()=>setDiaryMode('list')}>Lista</button><button aria-pressed={diaryMode==='calendar'} onClick={()=>setDiaryMode('calendar')}>Naptár</button></div>}
 {view==='naplo'&&diaryMode==='calendar'&&<div hidden={!!selected}><div className="page-heading"><div><span className="eyebrow">A RENDSZERESSÉGED NYOMA</span><h1>Edzésnaptár</h1></div><button className="primary" onClick={()=>begin()}><Plus size={20}/> Új edzés</button></div><WorkoutCalendar workouts={workouts} onOpen={setSelected}/></div>}
 {view==='naplo'&&!selected&&diaryMode==='list'&&<><div className="page-heading"><div><span className="eyebrow">MINDEN SOROZAT SZÁMÍT</span><h1>Edzésnaplód</h1></div><button className="primary" onClick={()=>begin()}><Plus size={20}/> Új edzés</button></div><div className="stats"><div><strong>{workouts.length}<span> edzés</span></strong><small>A naplódban</small></div><div><strong>{fmt(workouts.reduce((n:number,w:Row)=>n+volume(w),0)/1000)}<span> t</span></strong><small>Összes megmozgatott súly</small></div><div><strong>{data.bodyweights.length?fmt(ordered(data.bodyweights)[0].weight):'—'}<span> kg</span></strong><small>Legutóbbi testsúly</small></div></div>{last&&<section className="last-workout"><div><span className="eyebrow">LEGUTÓBB · {date(last.date)}</span><h2>{last.notes||'Edzés'}</h2><p>{last.exercises.length} gyakorlat · {last.exercises.reduce((n:number,e:Row)=>n+e.sets.length,0)} sorozat · {fmt(volume(last))} kg</p></div><button className="secondary" onClick={()=>begin(last)}>Megismétlem <ArrowUpRight size={18}/></button></section>}<div className="section-heading"><h2>Korábbi edzések <small>{filtered.length}</small></h2><div className="search"><Search size={18}/><input aria-label="Edzések keresése" placeholder="Edzés vagy gyakorlat keresése" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="history">{filtered.map((w:Row)=><button key={w.id} className="history-row" onClick={()=>setSelected(w)}><div className="calendar-tile"><strong>{new Date(w.date).getUTCDate()}</strong><small>{new Date(w.date).toLocaleDateString('hu-HU',{month:'short',timeZone:'UTC'})}</small></div><div className="history-title"><h3>{w.notes||'Edzés'}</h3><small>{w.exercises.length} gyakorlat · {w.exercises.reduce((n:number,e:Row)=>n+e.sets.length,0)} sorozat · {new Date(w.date).getUTCFullYear()}</small></div><strong className="volume">{fmt(volume(w))} <small>kg</small></strong><ArrowUpRight size={20}/></button>)}{!filtered.length&&<p className="empty">{search?'Nincs találat erre a keresésre.':'Még nincs edzés. Indítsd el az elsőt vagy tölts be egy mentést.'}</p>}</div></>}
 {view==='naplo'&&selected&&<><button className="text-button" onClick={()=>setSelected(null)}><ArrowLeft size={18}/> {diaryMode==='calendar'?'Vissza a naptárhoz':'Vissza a naplóhoz'}</button><span className="eyebrow">{date(selected.date)}</span><h1>{selected.notes||'Edzés'}</h1><div className="actions"><button className="primary" onClick={()=>begin(selected)}>Megismétlem</button><button className="secondary" onClick={()=>{if(draft){setError('Előbb fejezd be a folyamatban lévő edzést.');return;}act(()=>{const w=clone(selected);persist(data,w,withDraft(meta,w,true));setView('edzes');});}}>Szerkesztés</button><button className="secondary" onClick={()=>{const name=prompt('Sablon neve',selected.notes||'Saját edzés');if(name)act(()=>{const n=clone(data);n.templates.push(templateFrom(selected,name));persist(n);setNotice('Sablon elmentve.');});}}>Mentés sablonként</button></div>{selected.exercises.map((e:Row,i:number)=><section className="card" key={i}><small>{e.muscle}</small><h3>{e.name}</h3><div className="set-chips">{e.sets.map((s:Row,j:number)=><span key={j}>{fmt(s.weight)} kg × {s.reps}</span>)}</div></section>)}</>}
 {view==='edzes'&&draft&&<WorkoutEditor data={data} draft={draft} meta={meta} onChange={(d,m,label)=>commitEdit(data,d,m,label)} onError={setError} onSwap={i=>{setSwapError('');setSwapIndex(i);}} onAdd={()=>{setPick(true);setSearch('');}} onSave={save} onCheckpoint={checkpoint} onDownload={exportFull} onDiscard={()=>act(()=>{const m=withDraft(meta,null);m.timer={end:null,remaining:m.defaultRest};commitEdit(data,null,m,'Edzés elvetése');setView('naplo');})} onTemplateOrder={id=>act(()=>{commitEdit(saveTemplateOrder(data,draft,id),draft,meta,'Sablon sorrendje');setNotice('A sorrend elmentve a kiválasztott sablonba.');})} onTimerEnd={()=>act(()=>{const m=clone(meta);m.timer={end:null,remaining:0};persist(data,draft,m);setNotice('Letelt a pihenő. Jöhet a következő sorozat!');navigator.vibrate?.([200,100,200]);})}/>}
 {view==='sablon'&&<><span className="eyebrow">KEVESEBB BEÍRÁS, TÖBB EDZÉS</span><h1>Saját sablonjaid</h1><p>Az indításkor a gyakorlatok legutóbbi sorozatai töltődnek be. Edzés közben módosíthatod őket.</p><div className="template-grid">{data.templates.map((t:Row,i:number)=><TemplateCard key={t.id} template={t} index={i} onStart={()=>begin(t,true)} onRename={()=>{const name=prompt('Sablon új neve',t.name);if(name?.trim())act(()=>{const n=clone(data);n.templates.find((x:Row)=>x.id===t.id).name=name.trim();persist(n);});}} onMove={(from,to)=>act(()=>{const n=clone(data);const target=n.templates.find((x:Row)=>x.id===t.id);target.exercises=moveItem(target.exercises,from,to);commitEdit(n,draft,meta,'Sablon sorrendje');})}/>)}</div>{!data.templates.length&&<p className="empty">Egy elmentett edzés részleteinél a „Mentés sablonként” gombbal készíthetsz sablont.</p>}</>}
 {view==='gyakorlat'&&<><span className="eyebrow">A GYAKORLATTÁRAD</span><h1>Gyakorlatok <em>{data.exercises.length}</em></h1><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} aria-label="Gyakorlat keresése" placeholder="Név vagy izomcsoport"/></div><section className="card"><h3>Új saját gyakorlat</h3><form className="inline-form" onSubmit={e=>{e.preventDefault();act(()=>{if(!exerciseName.trim())throw new Error('Add meg a gyakorlat nevét.');const n=clone(data);n.exercises.push({id:newId(),name:exerciseName.trim(),muscle,muscles:[]});persist(n);setExerciseName('');setNotice('Gyakorlat hozzáadva.');});}}><label>Név<input value={exerciseName} onChange={e=>setExerciseName(e.target.value)} required/></label><label>Izomcsoport<select value={muscle} onChange={e=>setMuscle(e.target.value)}>{['Mell','Hát','Láb','Váll','Bicepsz','Tricepsz','Has','Egyéb'].map(m=><option key={m}>{m}</option>)}</select></label><button className="primary">Hozzáadás</button></form></section><div className="history">{exercises.map((e:Row)=><button className="history-row" key={e.id} onClick={()=>{setProgressId(e.id);setView('fejlodes');}}><div className="exercise-icon"><Dumbbell size={20}/></div><div className="history-title"><h3>{e.name}</h3><small>{e.muscle}</small></div><ArrowUpRight size={18}/></button>)}</div></>}
 {view==='fejlodes'&&<><span className="eyebrow">AZ ELVÉGZETT MUNKA NYOMA</span><h1>Fejlődésed</h1><section className="card"><h2>Gyakorlat története</h2><label>Gyakorlat<select value={progressId} onChange={e=>setProgressId(e.target.value)}><option value="">Válassz gyakorlatot</option>{data.exercises.map((e:Row)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>{progressId&&<><label className="exercise-note">Megjegyzés a gyakorlathoz<textarea rows={3} maxLength={5000} placeholder="Gépbeállítás, fogás vagy más emlékeztető" value={meta.exerciseNotes[progressId]||''} onChange={e=>act(()=>persist(data,draft,{...meta,exerciseNotes:{...meta.exerciseNotes,[progressId]:e.target.value}}))}/><small>Edzés közben és a következő alkalommal is megjelenik.</small></label><p className="record">Korábbi / becsült 1RM rekord: <em>{fmt(data.prs[progressId]||0)} kg</em></p><small>A mentésben tárolt rekordot megőrizzük; az új sorozatokból Epley-becslést számolunk.</small><div className="progress-list">{workouts.filter((w:Row)=>w.exercises.some((e:Row)=>e.exerciseId===progressId)).map((w:Row)=>{const sets=w.exercises.filter((e:Row)=>e.exerciseId===progressId).flatMap((e:Row)=>e.sets);const max=Math.max(0,...sets.map((s:Row)=>s.weight));return <div key={w.id}><span>{date(w.date)}</span><strong>{fmt(max)} kg</strong><small>{sets.map((s:Row)=>`${fmt(s.weight)} × ${s.reps}`).join(' · ')}</small><div className="bar"><i style={{width:`${Math.min(100,max/(data.prs[progressId]||max||1)*100)}%`}}/></div></div>})}</div>{!workouts.some((w:Row)=>w.exercises.some((e:Row)=>e.exerciseId===progressId))&&<p className="empty">Ehhez a gyakorlathoz még nincs rögzített edzés.</p>}</>}</section><section className="card"><h2>Testsúlynapló</h2><form className="inline-form" onSubmit={e=>{e.preventDefault();act(()=>{const kg=Number(weight);if(!Number.isFinite(kg)||kg<=0||!weightDate)throw new Error('Adj meg érvényes dátumot és pozitív testsúlyt.');const n=clone(data);n.bodyweights.push({id:newId(),date:Date.parse(weightDate+'T00:00:00Z'),weight:kg});persist(validateBackup(n));setWeight('');setNotice('Testsúly elmentve.');});}}><label>Dátum<input type="date" required value={weightDate} onChange={e=>setWeightDate(e.target.value)}/></label><label>Testsúly (kg)<input type="number" required inputMode="decimal" min="0.1" step="any" value={weight} onChange={e=>setWeight(e.target.value)}/></label><button className="primary">Rögzítés</button></form><div className="weight-list">{ordered(data.bodyweights).map((b:Row)=><div key={b.id}><span>{date(b.date)}</span><strong>{fmt(b.weight)} kg</strong><button className="icon-button danger" aria-label={`${date(b.date)} testsúly törlése`} onClick={()=>{if(confirm('Törlöd ezt a testsúlymérést?'))act(()=>{const n=clone(data);n.bodyweights=n.bodyweights.filter((x:Row)=>x.id!==b.id);persist(n);});}}><Trash2 size={16}/></button></div>)}</div></section></>}
 {view==='mentes'&&<><div className="backup-summary"><small>Az utolsó export óta: {meta.dirtyWorkoutIds.length} új vagy módosított edzés. Emlékeztető 5 edzés után.</small>{meta.lastExportAt&&<small>Utolsó export: {new Date(meta.lastExportAt).toLocaleString('hu-HU')}</small>}</div><span className="eyebrow">A NAPLÓD VELED MARAD</span><h1>Biztonsági mentések</h1><section className="card"><h2>Teljes mentés a folytatáshoz</h2><p>A napló mellett a félbehagyott edzést, az elvégzett sorozatok pipáit, a gyakorlatmegjegyzéseket és a beállításokat is tartalmazza. Ebbe a webappba tölthető vissza, másik eszközön is.</p><button className="primary" onClick={exportFull}><Download size={18}/> Teljes mentés letöltése</button></section><section className="card"><Download className="accent" size={28}/><h2>Vissza az Edzésnaplóba</h2><p>A letöltött JSON a régi app 2-es verziójú szerkezetét követi, az eredeti mezők megőrzésével. A régi appban való tényleges visszatöltést annak működésekor lehet ellenőrizni. A gyakorlatmegjegyzések és a webapp beállításai csak a teljes mentésbe kerülnek.</p><button className="primary" onClick={exportData}><Download size={18}/> JSON-mentés letöltése</button>{draft&&<p>A régi app exportjához előbb zárd le az edzést. A félbehagyott edzés és a gyakorlatmegjegyzések a teljes mentésben őrizhetők meg.</p>}</section><section className="card"><h2>Mentés betöltése</h2><p>Régi vagy ebből az appból exportált mentést is választhatsz. A fájlt ellenőrizzük, majd jóváhagyás után lecseréljük a helyi naplót.</p><button className="secondary" onClick={()=>file.current?.click()}><Upload size={18}/> JSON-fájl kiválasztása</button><button className="text-button" onClick={()=>act(()=>{const previous=localStorage.getItem(KEY+'-previous');if(!previous)throw new Error('Még nincs import előtti helyi másolat.');const saved=JSON.parse(previous);if(confirm('Visszaállítod az utolsó import előtti állapotot? A jelenlegi naplót előbb letöltjük.')){download(exportSnapshot(data,draft,meta),'edzesnaplom-visszaallitas-elott.json');persist(validateBackup(saved.data),saved.draft||null,hydrateMeta(saved.data,saved.draft||null,saved.meta));setNotice('Az import előtti állapot visszaállítva.');}})}>Import előtti állapot visszaállítása</button></section><section className="card"><ShieldCheck size={26}/><h2>Tárolás ezen az eszközön</h2><p>Az edzésadatok ebben a böngészőben tárolódnak; nincs automatikus szinkronizálás. A böngészőadatok törlése a naplót is törli. Rendszeresen tölts le JSON-mentést, különösen eszközváltás előtt.</p><p>Telefonon nyisd meg az appot, és a böngésző menüjében válaszd a „Hozzáadás a kezdőképernyőhöz” lehetőséget. {offline?'Az alkalmazás offline használatra is készen áll.':'Az offline mód az első sikeres online betöltés után készül el.'}</p></section></>}
 </main>{importReview}{swapIndex!==null&&draft&&<ExerciseSwapDialog data={data} draft={draft} index={swapIndex} onClose={()=>setSwapIndex(null)} onReplace={performSwap} error={swapError}/>}{pick&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="picker-title"><div className="section-heading"><h2 id="picker-title">Gyakorlat hozzáadása</h2><button className="secondary" onClick={()=>setPick(false)}>Bezárás</button></div><input autoFocus aria-label="Gyakorlat keresése" placeholder="Keresés név vagy izomcsoport alapján" value={search} onChange={e=>setSearch(e.target.value)}/><div className="picker-list">{exercises.map((e:Row)=><button key={e.id} onClick={()=>{edit(d=>{const last=workouts.flatMap((w:Row)=>w.exercises).find((x:Row)=>x.exerciseId===e.id);d.exercises.push({exerciseId:e.id,name:e.name,muscle:e.muscle,sets:clone(last?.sets?.length?last.sets:[{weight:0,reps:10}])});});setPick(false);}}><span>{e.name}<small>{e.muscle}</small></span><Plus size={18}/></button>)}{!exercises.length&&<p className="empty">Nincs találat. A Gyakorlatok fülön adhatsz hozzá saját gyakorlatot.</p>}</div></section></div>}</div>;
}


