'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeftRight,Check,Pause,Play,Plus,RotateCcw,Timer,Trash2} from 'lucide-react';
import {clone,dateInput,ordered} from '../lib/backup.mjs';
import {checkSet,counts,moveDraft,removeSet,removeExercise,sameExercises,validSet} from '../lib/session.mjs';
import OrderControls from './order-controls';
type Row=Record<string,any>;
type Props={data:Row;draft:Row;meta:Row;onChange:(draft:Row,meta:Row,undoLabel?:string)=>void;onError:(message:string)=>void;onSwap:(i:number)=>void;onSave:()=>void;onDiscard:()=>void;onTemplateOrder:(id:string)=>void;onAdd:()=>void;onTimerEnd:()=>void};
const fmt=(n:number)=>new Intl.NumberFormat('hu-HU',{maximumFractionDigits:1}).format(n);
function RestTimer({meta,onUpdate,onEnd}:{meta:Row;onUpdate:(meta:Row)=>void;onEnd:()=>void}){
 const [now,setNow]=useState(Date.now()),handled=useRef<number|null>(null),endCallback=useRef(onEnd);endCallback.current=onEnd;
 const end=meta.timer.end;
 useEffect(()=>{if(!end)return;function tick(){const n=Date.now();setNow(n);if(n>=end&&handled.current!==end){handled.current=end;endCallback.current();}}tick();const id=setInterval(tick,250);return()=>clearInterval(id);},[end]);
 const remaining=end?Math.max(0,Math.ceil((end-now)/1000)):meta.timer.remaining;
 function update(fn:(m:Row)=>void){const m=clone(meta);fn(m);onUpdate(m);}
 return <section className="rest-panel"><div className="timer"><Timer size={20}/><span>Pihenő</span><strong role="timer" aria-label="Hátralévő pihenő">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong><label className="timer-default"><span>Alap pihenő</span><select aria-label="Alapértelmezett pihenő" value={meta.defaultRest} onChange={e=>update(m=>{m.defaultRest=Number(e.target.value);if(!m.timer.end)m.timer.remaining=m.defaultRest;})}>{[30,60,90,120,180,300].map(n=><option value={n} key={n}>{n} mp</option>)}</select></label><button className="icon-button" aria-label={end?'Pihenő szüneteltetése':'Pihenő indítása'} onClick={()=>update(m=>{const seconds=remaining||m.defaultRest;m.timer=end?{end:null,remaining}:{end:Date.now()+seconds*1000,remaining:seconds};})}>{end?<Pause size={18}/>:<Play size={18}/>}</button><button className="icon-button" aria-label="Időzítő visszaállítása" onClick={()=>update(m=>{m.timer={end:null,remaining:m.defaultRest};})}><RotateCcw size={18}/></button></div><label className="check-label"><input type="checkbox" checked={meta.autoRest} onChange={e=>update(m=>{m.autoRest=e.target.checked;})}/> Pihenő automatikus indítása a sorozat kipipálásakor</label></section>;
}
export default function WorkoutEditor({data,draft,meta,onChange,onError,onSwap,onSave,onDiscard,onTemplateOrder,onTimerEnd,onAdd}:Props){
 const [templateId,setTemplateId]=useState('');
 const progress=counts(draft,meta),templates=data.templates.filter((t:Row)=>sameExercises(t,draft));
 const scope='workout-'+draft.id;
 function run(fn:()=>void){try{fn();}catch(e){onError((e as Error).message);}}
 function change(fn:(d:Row,m:Row)=>void,label?:string){run(()=>{const d=clone(draft),m=clone(meta);fn(d,m);onChange(d,m,label);});}
 function move(from:number,to:number){run(()=>{const r=moveDraft(draft,meta,from,to);onChange(r.draft,r.meta,'Sorrendmódosítás');});}
 return <>
 <div className="page-heading"><div><span className="eyebrow">{data.workouts.some((w:Row)=>w.id===draft.id)?'EDZÉS SZERKESZTÉSE':'FOLYAMATBAN'}</span><h1>A mai munka</h1></div><small><Check size={15}/> Automatikus helyi mentés</small></div>
 <div className="editor-head"><label>Edzés neve / megjegyzés<input value={draft.notes} placeholder="Például: Push" onChange={e=>change(d=>{d.notes=e.target.value;})}/></label><label>Dátum<input type="date" required value={dateInput(draft.date)} onChange={e=>{if(e.target.value)change(d=>{d.date=Date.parse(e.target.value+'T00:00:00Z');});}}/></label></div>
 <div className="workout-progress"><span><strong>{progress.done}</strong> / {progress.total} sorozat kész</span><progress value={progress.done} max={progress.total||1} aria-label="Elvégzett sorozatok"/><small>A korábbi értékek javaslatok. Pipáld ki, amit elvégeztél.</small></div>
 <RestTimer meta={meta} onUpdate={m=>run(()=>onChange(draft,m))} onEnd={onTimerEnd}/>
 {draft.exercises.map((e:Row,i:number)=>{const previous=ordered(data.workouts).filter((w:Row)=>w.id!==draft.id).flatMap((w:Row)=>w.exercises).find((x:Row)=>x.exerciseId===e.exerciseId);return <section className="card exercise-card" key={i} data-order-index={i} data-order-scope={scope}>
 <div className="section-heading"><div><small>{String(i+1).padStart(2,'0')} / {e.muscle}</small><h3>{e.name}</h3></div><div className="exercise-actions"><OrderControls index={i} count={draft.exercises.length} name={e.name} scope={scope} onMove={move}/><button className="secondary swap-trigger" aria-label={e.name+' cseréje'} onClick={()=>onSwap(i)}><ArrowLeftRight size={17}/> Csere</button><button className="icon-button danger" aria-label={e.name+' eltávolítása'} onClick={()=>run(()=>{const r=removeExercise(draft,meta,i);onChange(r.draft,r.meta,'Gyakorlat törlése');})}><Trash2 size={18}/></button></div></div>
 {previous&&<p className="previous">Legutóbb: {previous.sets.map((s:Row)=>`${fmt(s.weight)} × ${s.reps}`).join(' · ')}</p>}
 <label className="exercise-rest">Pihenő ennél a gyakorlatnál<select aria-label={e.name+' pihenőideje'} value={meta.restByExercise[e.exerciseId]??''} onChange={ev=>change((d,m)=>{if(ev.target.value==='')delete m.restByExercise[e.exerciseId];else m.restByExercise[e.exerciseId]=Number(ev.target.value);})}><option value="">Alapértelmezett ({meta.defaultRest} mp)</option>{[0,30,60,90,120,180,300].map(n=><option value={n} key={n}>{n===0?'Nincs automatikus pihenő':`${n} mp`}</option>)}</select></label>
 <div className="set-row tracked set-label"><span>Sor.</span><span>Súly (kg)</span><span>Ismétlés</span><span>Kész</span><span/></div>
 {e.sets.map((s:Row,j:number)=>{const done=meta.activity.checks[i]?.[j]===true;return <div className={'set-row tracked '+(done?'done':'')} key={j}><span className="set-number">{j+1}</span><input aria-label={`${e.name}, ${j+1}. sorozat súlya`} type="number" inputMode="decimal" min="0" step="any" value={s.weight} onChange={ev=>change((d,m)=>{d.exercises[i].sets[j].weight=ev.target.value===''?'':Number(ev.target.value);if(!validSet(d.exercises[i].sets[j]))m.activity.checks[i][j]=false;})}/><input aria-label={`${e.name}, ${j+1}. sorozat ismétlése`} type="number" inputMode="numeric" min="1" step="1" value={s.reps} onChange={ev=>change((d,m)=>{d.exercises[i].sets[j].reps=ev.target.value===''?'':Number(ev.target.value);if(!validSet(d.exercises[i].sets[j]))m.activity.checks[i][j]=false;})}/><input className="set-check" type="checkbox" aria-label={`${e.name}, ${j+1}. sorozat elvégezve`} checked={done} onChange={ev=>run(()=>onChange(draft,checkSet(draft,meta,i,j,ev.target.checked)))}/><button className="icon-button" aria-label={`${e.name}, ${j+1}. sorozat törlése`} onClick={()=>run(()=>{const r=removeSet(draft,meta,i,j);onChange(r.draft,r.meta,'Sorozat törlése');})}><Trash2 size={16}/></button></div>;})}
 <button className="text-button accent" onClick={()=>change((d,m)=>{d.exercises[i].sets.push(clone(e.sets.at(-1)||{weight:0,reps:10}));m.activity.checks[i].push(false);})}><Plus size={17}/> Sorozat hozzáadása</button></section>;})}
 {!draft.exercises.length&&<p className="empty">Válassz gyakorlatot az első sorozathoz.</p>}
 <button className="add-exercise" onClick={onAdd}><Plus size={20}/> Gyakorlat hozzáadása</button><details className="template-order-save"><summary>A mostani sorrend mentése sablonba</summary><p>Csak a kiválasztott sablon sorrendje változik. A sorozatok és súlyok nem kerülnek bele.</p>{templates.length?<div className="inline-form"><label>Sablon<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Válassz sablont</option>{templates.map((t:Row)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button className="secondary" disabled={!templates.some((t:Row)=>t.id===templateId)} onClick={()=>onTemplateOrder(templateId)}>Sorrend mentése</button></div>:<p>Nincs pontosan ezekből a gyakorlatokból álló sablon. Az edzés elmentése után új sablont készíthetsz belőle.</p>}</details>
 <div className="finish-bar"><button className="text-button danger" onClick={onDiscard}>Edzés elvetése</button><button className="primary" onClick={onSave}><Check size={20}/> Edzés mentése</button></div>
 </>;
}
